// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.0
// source: blog/v1/blog.proto

package v1

import (
	model "github.com/SoLikeWind/XuanXiang/api/common/model"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListArticleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int64                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int64                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Tag           string                 `protobuf:"bytes,3,opt,name=tag,proto3" json:"tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListArticleRequest) Reset() {
	*x = ListArticleRequest{}
	mi := &file_blog_v1_blog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListArticleRequest) ProtoMessage() {}

func (x *ListArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blog_v1_blog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListArticleRequest.ProtoReflect.Descriptor instead.
func (*ListArticleRequest) Descriptor() ([]byte, []int) {
	return file_blog_v1_blog_proto_rawDescGZIP(), []int{0}
}

func (x *ListArticleRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListArticleRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListArticleRequest) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

type ListArticleReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Articles      []*model.Article       `protobuf:"bytes,1,rep,name=articles,proto3" json:"articles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListArticleReply) Reset() {
	*x = ListArticleReply{}
	mi := &file_blog_v1_blog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListArticleReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListArticleReply) ProtoMessage() {}

func (x *ListArticleReply) ProtoReflect() protoreflect.Message {
	mi := &file_blog_v1_blog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListArticleReply.ProtoReflect.Descriptor instead.
func (*ListArticleReply) Descriptor() ([]byte, []int) {
	return file_blog_v1_blog_proto_rawDescGZIP(), []int{1}
}

func (x *ListArticleReply) GetArticles() []*model.Article {
	if x != nil {
		return x.Articles
	}
	return nil
}

type GetArticleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArticleRequest) Reset() {
	*x = GetArticleRequest{}
	mi := &file_blog_v1_blog_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArticleRequest) ProtoMessage() {}

func (x *GetArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blog_v1_blog_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArticleRequest.ProtoReflect.Descriptor instead.
func (*GetArticleRequest) Descriptor() ([]byte, []int) {
	return file_blog_v1_blog_proto_rawDescGZIP(), []int{2}
}

func (x *GetArticleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetArticleReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Article       *model.Article         `protobuf:"bytes,1,opt,name=article,proto3" json:"article,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArticleReply) Reset() {
	*x = GetArticleReply{}
	mi := &file_blog_v1_blog_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArticleReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArticleReply) ProtoMessage() {}

func (x *GetArticleReply) ProtoReflect() protoreflect.Message {
	mi := &file_blog_v1_blog_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArticleReply.ProtoReflect.Descriptor instead.
func (*GetArticleReply) Descriptor() ([]byte, []int) {
	return file_blog_v1_blog_proto_rawDescGZIP(), []int{3}
}

func (x *GetArticleReply) GetArticle() *model.Article {
	if x != nil {
		return x.Article
	}
	return nil
}

type CreateArticleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Summary       string                 `protobuf:"bytes,2,opt,name=summary,proto3" json:"summary,omitempty"`
	Image         *string                `protobuf:"bytes,3,opt,name=image,proto3,oneof" json:"image,omitempty"`
	ContentMd     string                 `protobuf:"bytes,4,opt,name=content_md,json=contentMd,proto3" json:"content_md,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateArticleRequest) Reset() {
	*x = CreateArticleRequest{}
	mi := &file_blog_v1_blog_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateArticleRequest) ProtoMessage() {}

func (x *CreateArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blog_v1_blog_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateArticleRequest.ProtoReflect.Descriptor instead.
func (*CreateArticleRequest) Descriptor() ([]byte, []int) {
	return file_blog_v1_blog_proto_rawDescGZIP(), []int{4}
}

func (x *CreateArticleRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateArticleRequest) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *CreateArticleRequest) GetImage() string {
	if x != nil && x.Image != nil {
		return *x.Image
	}
	return ""
}

func (x *CreateArticleRequest) GetContentMd() string {
	if x != nil {
		return x.ContentMd
	}
	return ""
}

type CreateArticleReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Article       *model.Article         `protobuf:"bytes,1,opt,name=article,proto3" json:"article,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateArticleReply) Reset() {
	*x = CreateArticleReply{}
	mi := &file_blog_v1_blog_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateArticleReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateArticleReply) ProtoMessage() {}

func (x *CreateArticleReply) ProtoReflect() protoreflect.Message {
	mi := &file_blog_v1_blog_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateArticleReply.ProtoReflect.Descriptor instead.
func (*CreateArticleReply) Descriptor() ([]byte, []int) {
	return file_blog_v1_blog_proto_rawDescGZIP(), []int{5}
}

func (x *CreateArticleReply) GetArticle() *model.Article {
	if x != nil {
		return x.Article
	}
	return nil
}

type UpdateArticleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         *string                `protobuf:"bytes,2,opt,name=title,proto3,oneof" json:"title,omitempty"`
	Summary       *string                `protobuf:"bytes,3,opt,name=summary,proto3,oneof" json:"summary,omitempty"`
	Image         *string                `protobuf:"bytes,4,opt,name=image,proto3,oneof" json:"image,omitempty"`
	ContentMd     *string                `protobuf:"bytes,5,opt,name=content_md,json=contentMd,proto3,oneof" json:"content_md,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateArticleRequest) Reset() {
	*x = UpdateArticleRequest{}
	mi := &file_blog_v1_blog_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateArticleRequest) ProtoMessage() {}

func (x *UpdateArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blog_v1_blog_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateArticleRequest.ProtoReflect.Descriptor instead.
func (*UpdateArticleRequest) Descriptor() ([]byte, []int) {
	return file_blog_v1_blog_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateArticleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateArticleRequest) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *UpdateArticleRequest) GetSummary() string {
	if x != nil && x.Summary != nil {
		return *x.Summary
	}
	return ""
}

func (x *UpdateArticleRequest) GetImage() string {
	if x != nil && x.Image != nil {
		return *x.Image
	}
	return ""
}

func (x *UpdateArticleRequest) GetContentMd() string {
	if x != nil && x.ContentMd != nil {
		return *x.ContentMd
	}
	return ""
}

type UpdateArticleReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Article       *model.Article         `protobuf:"bytes,1,opt,name=article,proto3" json:"article,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateArticleReply) Reset() {
	*x = UpdateArticleReply{}
	mi := &file_blog_v1_blog_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateArticleReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateArticleReply) ProtoMessage() {}

func (x *UpdateArticleReply) ProtoReflect() protoreflect.Message {
	mi := &file_blog_v1_blog_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateArticleReply.ProtoReflect.Descriptor instead.
func (*UpdateArticleReply) Descriptor() ([]byte, []int) {
	return file_blog_v1_blog_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateArticleReply) GetArticle() *model.Article {
	if x != nil {
		return x.Article
	}
	return nil
}

type DeleteArticleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteArticleRequest) Reset() {
	*x = DeleteArticleRequest{}
	mi := &file_blog_v1_blog_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteArticleRequest) ProtoMessage() {}

func (x *DeleteArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blog_v1_blog_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteArticleRequest.ProtoReflect.Descriptor instead.
func (*DeleteArticleRequest) Descriptor() ([]byte, []int) {
	return file_blog_v1_blog_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteArticleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListTagRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int64                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int64                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTagRequest) Reset() {
	*x = ListTagRequest{}
	mi := &file_blog_v1_blog_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTagRequest) ProtoMessage() {}

func (x *ListTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blog_v1_blog_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTagRequest.ProtoReflect.Descriptor instead.
func (*ListTagRequest) Descriptor() ([]byte, []int) {
	return file_blog_v1_blog_proto_rawDescGZIP(), []int{9}
}

func (x *ListTagRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListTagRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListTagReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Tags          []*model.Tag           `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTagReply) Reset() {
	*x = ListTagReply{}
	mi := &file_blog_v1_blog_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTagReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTagReply) ProtoMessage() {}

func (x *ListTagReply) ProtoReflect() protoreflect.Message {
	mi := &file_blog_v1_blog_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTagReply.ProtoReflect.Descriptor instead.
func (*ListTagReply) Descriptor() ([]byte, []int) {
	return file_blog_v1_blog_proto_rawDescGZIP(), []int{10}
}

func (x *ListTagReply) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListTagReply) GetTags() []*model.Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

type GetTagRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTagRequest) Reset() {
	*x = GetTagRequest{}
	mi := &file_blog_v1_blog_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTagRequest) ProtoMessage() {}

func (x *GetTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blog_v1_blog_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTagRequest.ProtoReflect.Descriptor instead.
func (*GetTagRequest) Descriptor() ([]byte, []int) {
	return file_blog_v1_blog_proto_rawDescGZIP(), []int{11}
}

func (x *GetTagRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetTagReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           *model.Tag             `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTagReply) Reset() {
	*x = GetTagReply{}
	mi := &file_blog_v1_blog_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTagReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTagReply) ProtoMessage() {}

func (x *GetTagReply) ProtoReflect() protoreflect.Message {
	mi := &file_blog_v1_blog_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTagReply.ProtoReflect.Descriptor instead.
func (*GetTagReply) Descriptor() ([]byte, []int) {
	return file_blog_v1_blog_proto_rawDescGZIP(), []int{12}
}

func (x *GetTagReply) GetTag() *model.Tag {
	if x != nil {
		return x.Tag
	}
	return nil
}

type CreateTagRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTagRequest) Reset() {
	*x = CreateTagRequest{}
	mi := &file_blog_v1_blog_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTagRequest) ProtoMessage() {}

func (x *CreateTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blog_v1_blog_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTagRequest.ProtoReflect.Descriptor instead.
func (*CreateTagRequest) Descriptor() ([]byte, []int) {
	return file_blog_v1_blog_proto_rawDescGZIP(), []int{13}
}

func (x *CreateTagRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateTagReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           *model.Tag             `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTagReply) Reset() {
	*x = CreateTagReply{}
	mi := &file_blog_v1_blog_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTagReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTagReply) ProtoMessage() {}

func (x *CreateTagReply) ProtoReflect() protoreflect.Message {
	mi := &file_blog_v1_blog_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTagReply.ProtoReflect.Descriptor instead.
func (*CreateTagReply) Descriptor() ([]byte, []int) {
	return file_blog_v1_blog_proto_rawDescGZIP(), []int{14}
}

func (x *CreateTagReply) GetTag() *model.Tag {
	if x != nil {
		return x.Tag
	}
	return nil
}

type UpdateTagRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTagRequest) Reset() {
	*x = UpdateTagRequest{}
	mi := &file_blog_v1_blog_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTagRequest) ProtoMessage() {}

func (x *UpdateTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blog_v1_blog_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTagRequest.ProtoReflect.Descriptor instead.
func (*UpdateTagRequest) Descriptor() ([]byte, []int) {
	return file_blog_v1_blog_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateTagRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateTagRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteTagRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTagRequest) Reset() {
	*x = DeleteTagRequest{}
	mi := &file_blog_v1_blog_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTagRequest) ProtoMessage() {}

func (x *DeleteTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blog_v1_blog_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTagRequest.ProtoReflect.Descriptor instead.
func (*DeleteTagRequest) Descriptor() ([]byte, []int) {
	return file_blog_v1_blog_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteTagRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_blog_v1_blog_proto protoreflect.FileDescriptor

const file_blog_v1_blog_proto_rawDesc = "" +
	"\n" +
	"\x12blog/v1/blog.proto\x12\ablog.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1dcommon/model/blog_field.proto\"W\n" +
	"\x12ListArticleRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x03R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x03R\bpageSize\x12\x10\n" +
	"\x03tag\x18\x03 \x01(\tR\x03tag\"E\n" +
	"\x10ListArticleReply\x121\n" +
	"\barticles\x18\x01 \x03(\v2\x15.common.model.ArticleR\barticles\"#\n" +
	"\x11GetArticleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"B\n" +
	"\x0fGetArticleReply\x12/\n" +
	"\aarticle\x18\x01 \x01(\v2\x15.common.model.ArticleR\aarticle\"\x8a\x01\n" +
	"\x14CreateArticleRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x18\n" +
	"\asummary\x18\x02 \x01(\tR\asummary\x12\x19\n" +
	"\x05image\x18\x03 \x01(\tH\x00R\x05image\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"content_md\x18\x04 \x01(\tR\tcontentMdB\b\n" +
	"\x06_image\"E\n" +
	"\x12CreateArticleReply\x12/\n" +
	"\aarticle\x18\x01 \x01(\v2\x15.common.model.ArticleR\aarticle\"\xce\x01\n" +
	"\x14UpdateArticleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\x05title\x18\x02 \x01(\tH\x00R\x05title\x88\x01\x01\x12\x1d\n" +
	"\asummary\x18\x03 \x01(\tH\x01R\asummary\x88\x01\x01\x12\x19\n" +
	"\x05image\x18\x04 \x01(\tH\x02R\x05image\x88\x01\x01\x12\"\n" +
	"\n" +
	"content_md\x18\x05 \x01(\tH\x03R\tcontentMd\x88\x01\x01B\b\n" +
	"\x06_titleB\n" +
	"\n" +
	"\b_summaryB\b\n" +
	"\x06_imageB\r\n" +
	"\v_content_md\"E\n" +
	"\x12UpdateArticleReply\x12/\n" +
	"\aarticle\x18\x01 \x01(\v2\x15.common.model.ArticleR\aarticle\"&\n" +
	"\x14DeleteArticleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"A\n" +
	"\x0eListTagRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x03R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x03R\bpageSize\"K\n" +
	"\fListTagReply\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12%\n" +
	"\x04tags\x18\x02 \x03(\v2\x11.common.model.TagR\x04tags\"\x1f\n" +
	"\rGetTagRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"2\n" +
	"\vGetTagReply\x12#\n" +
	"\x03tag\x18\x01 \x01(\v2\x11.common.model.TagR\x03tag\"&\n" +
	"\x10CreateTagRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"5\n" +
	"\x0eCreateTagReply\x12#\n" +
	"\x03tag\x18\x01 \x01(\v2\x11.common.model.TagR\x03tag\"6\n" +
	"\x10UpdateTagRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\"\n" +
	"\x10DeleteTagRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id2\xbc\a\n" +
	"\x04Blog\x12_\n" +
	"\vListArticle\x12\x1b.blog.v1.ListArticleRequest\x1a\x19.blog.v1.ListArticleReply\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/v1/blog/article\x12a\n" +
	"\n" +
	"GetArticle\x12\x1a.blog.v1.GetArticleRequest\x1a\x18.blog.v1.GetArticleReply\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/v1/blog/article/{id}\x12h\n" +
	"\rCreateArticle\x12\x1d.blog.v1.CreateArticleRequest\x1a\x1b.blog.v1.CreateArticleReply\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/v1/blog/article\x12h\n" +
	"\rUpdateArticle\x12\x1d.blog.v1.UpdateArticleRequest\x1a\x16.google.protobuf.Empty\" \x82\xd3\xe4\x93\x02\x1a:\x01*\x1a\x15/v1/blog/article/{id}\x12e\n" +
	"\rDeleteArticle\x12\x1d.blog.v1.DeleteArticleRequest\x1a\x16.google.protobuf.Empty\"\x1d\x82\xd3\xe4\x93\x02\x17*\x15/v1/blog/article/{id}\x12O\n" +
	"\aListTag\x12\x17.blog.v1.ListTagRequest\x1a\x15.blog.v1.ListTagReply\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/v1/blog/tag\x12Q\n" +
	"\x06GetTag\x12\x16.blog.v1.GetTagRequest\x1a\x14.blog.v1.GetTagReply\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/v1/blog/tag/{id}\x12X\n" +
	"\tCreateTag\x12\x19.blog.v1.CreateTagRequest\x1a\x17.blog.v1.CreateTagReply\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/v1/blog/tag\x12\\\n" +
	"\tUpdateTag\x12\x19.blog.v1.UpdateTagRequest\x1a\x16.google.protobuf.Empty\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\x1a\x11/v1/blog/tag/{id}\x12Y\n" +
	"\tDeleteTag\x12\x19.blog.v1.DeleteTagRequest\x1a\x16.google.protobuf.Empty\"\x19\x82\xd3\xe4\x93\x02\x13*\x11/v1/blog/tag/{id}B0Z.github.com/SoLikeWind/XuanXiang/api/blog/v1;v1b\x06proto3"

var (
	file_blog_v1_blog_proto_rawDescOnce sync.Once
	file_blog_v1_blog_proto_rawDescData []byte
)

func file_blog_v1_blog_proto_rawDescGZIP() []byte {
	file_blog_v1_blog_proto_rawDescOnce.Do(func() {
		file_blog_v1_blog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_blog_v1_blog_proto_rawDesc), len(file_blog_v1_blog_proto_rawDesc)))
	})
	return file_blog_v1_blog_proto_rawDescData
}

var file_blog_v1_blog_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_blog_v1_blog_proto_goTypes = []any{
	(*ListArticleRequest)(nil),   // 0: blog.v1.ListArticleRequest
	(*ListArticleReply)(nil),     // 1: blog.v1.ListArticleReply
	(*GetArticleRequest)(nil),    // 2: blog.v1.GetArticleRequest
	(*GetArticleReply)(nil),      // 3: blog.v1.GetArticleReply
	(*CreateArticleRequest)(nil), // 4: blog.v1.CreateArticleRequest
	(*CreateArticleReply)(nil),   // 5: blog.v1.CreateArticleReply
	(*UpdateArticleRequest)(nil), // 6: blog.v1.UpdateArticleRequest
	(*UpdateArticleReply)(nil),   // 7: blog.v1.UpdateArticleReply
	(*DeleteArticleRequest)(nil), // 8: blog.v1.DeleteArticleRequest
	(*ListTagRequest)(nil),       // 9: blog.v1.ListTagRequest
	(*ListTagReply)(nil),         // 10: blog.v1.ListTagReply
	(*GetTagRequest)(nil),        // 11: blog.v1.GetTagRequest
	(*GetTagReply)(nil),          // 12: blog.v1.GetTagReply
	(*CreateTagRequest)(nil),     // 13: blog.v1.CreateTagRequest
	(*CreateTagReply)(nil),       // 14: blog.v1.CreateTagReply
	(*UpdateTagRequest)(nil),     // 15: blog.v1.UpdateTagRequest
	(*DeleteTagRequest)(nil),     // 16: blog.v1.DeleteTagRequest
	(*model.Article)(nil),        // 17: common.model.Article
	(*model.Tag)(nil),            // 18: common.model.Tag
	(*emptypb.Empty)(nil),        // 19: google.protobuf.Empty
}
var file_blog_v1_blog_proto_depIdxs = []int32{
	17, // 0: blog.v1.ListArticleReply.articles:type_name -> common.model.Article
	17, // 1: blog.v1.GetArticleReply.article:type_name -> common.model.Article
	17, // 2: blog.v1.CreateArticleReply.article:type_name -> common.model.Article
	17, // 3: blog.v1.UpdateArticleReply.article:type_name -> common.model.Article
	18, // 4: blog.v1.ListTagReply.tags:type_name -> common.model.Tag
	18, // 5: blog.v1.GetTagReply.tag:type_name -> common.model.Tag
	18, // 6: blog.v1.CreateTagReply.tag:type_name -> common.model.Tag
	0,  // 7: blog.v1.Blog.ListArticle:input_type -> blog.v1.ListArticleRequest
	2,  // 8: blog.v1.Blog.GetArticle:input_type -> blog.v1.GetArticleRequest
	4,  // 9: blog.v1.Blog.CreateArticle:input_type -> blog.v1.CreateArticleRequest
	6,  // 10: blog.v1.Blog.UpdateArticle:input_type -> blog.v1.UpdateArticleRequest
	8,  // 11: blog.v1.Blog.DeleteArticle:input_type -> blog.v1.DeleteArticleRequest
	9,  // 12: blog.v1.Blog.ListTag:input_type -> blog.v1.ListTagRequest
	11, // 13: blog.v1.Blog.GetTag:input_type -> blog.v1.GetTagRequest
	13, // 14: blog.v1.Blog.CreateTag:input_type -> blog.v1.CreateTagRequest
	15, // 15: blog.v1.Blog.UpdateTag:input_type -> blog.v1.UpdateTagRequest
	16, // 16: blog.v1.Blog.DeleteTag:input_type -> blog.v1.DeleteTagRequest
	1,  // 17: blog.v1.Blog.ListArticle:output_type -> blog.v1.ListArticleReply
	3,  // 18: blog.v1.Blog.GetArticle:output_type -> blog.v1.GetArticleReply
	5,  // 19: blog.v1.Blog.CreateArticle:output_type -> blog.v1.CreateArticleReply
	19, // 20: blog.v1.Blog.UpdateArticle:output_type -> google.protobuf.Empty
	19, // 21: blog.v1.Blog.DeleteArticle:output_type -> google.protobuf.Empty
	10, // 22: blog.v1.Blog.ListTag:output_type -> blog.v1.ListTagReply
	12, // 23: blog.v1.Blog.GetTag:output_type -> blog.v1.GetTagReply
	14, // 24: blog.v1.Blog.CreateTag:output_type -> blog.v1.CreateTagReply
	19, // 25: blog.v1.Blog.UpdateTag:output_type -> google.protobuf.Empty
	19, // 26: blog.v1.Blog.DeleteTag:output_type -> google.protobuf.Empty
	17, // [17:27] is the sub-list for method output_type
	7,  // [7:17] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_blog_v1_blog_proto_init() }
func file_blog_v1_blog_proto_init() {
	if File_blog_v1_blog_proto != nil {
		return
	}
	file_blog_v1_blog_proto_msgTypes[4].OneofWrappers = []any{}
	file_blog_v1_blog_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_blog_v1_blog_proto_rawDesc), len(file_blog_v1_blog_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_blog_v1_blog_proto_goTypes,
		DependencyIndexes: file_blog_v1_blog_proto_depIdxs,
		MessageInfos:      file_blog_v1_blog_proto_msgTypes,
	}.Build()
	File_blog_v1_blog_proto = out.File
	file_blog_v1_blog_proto_goTypes = nil
	file_blog_v1_blog_proto_depIdxs = nil
}
