// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package v1

import (
	fmt "fmt"
	errors "github.com/go-kratos/kratos/v2/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

// 无权限访问
func IsArticleAccessDenied(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReasonArticle_ARTICLE_ACCESS_DENIED.String() && e.Code == 403
}

// 无权限访问
func ErrorArticleAccessDenied(format string, args ...interface{}) *errors.Error {
	return errors.New(403, ErrorReasonArticle_ARTICLE_ACCESS_DENIED.String(), fmt.Sprintf(format, args...))
}

// 文章不存在
func IsArticleNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReasonArticle_ARTICLE_NOT_FOUND.String() && e.Code == 404
}

// 文章不存在
func ErrorArticleNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(404, ErrorReasonArticle_ARTICLE_NOT_FOUND.String(), fmt.Sprintf(format, args...))
}

// 标签不存在
func IsTagNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReasonTag_TAG_NOT_FOUND.String() && e.Code == 404
}

// 标签不存在
func ErrorTagNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(404, ErrorReasonTag_TAG_NOT_FOUND.String(), fmt.Sprintf(format, args...))
}
