// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.0
// source: blog/v1/error.proto

package v1

import (
	_ "github.com/go-kratos/kratos/v2/errors"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 文章模块错误 2001-2019
type ErrorReasonArticle int32

const (
	ErrorReasonArticle_ARTICLE_ACCESS_DENIED ErrorReasonArticle = 0 //无权限访问
	ErrorReasonArticle_ARTICLE_NOT_FOUND     ErrorReasonArticle = 1 //文章不存在
)

// Enum value maps for ErrorReasonArticle.
var (
	ErrorReasonArticle_name = map[int32]string{
		0: "ARTICLE_ACCESS_DENIED",
		1: "ARTICLE_NOT_FOUND",
	}
	ErrorReasonArticle_value = map[string]int32{
		"ARTICLE_ACCESS_DENIED": 0,
		"ARTICLE_NOT_FOUND":     1,
	}
)

func (x ErrorReasonArticle) Enum() *ErrorReasonArticle {
	p := new(ErrorReasonArticle)
	*p = x
	return p
}

func (x ErrorReasonArticle) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorReasonArticle) Descriptor() protoreflect.EnumDescriptor {
	return file_blog_v1_error_proto_enumTypes[0].Descriptor()
}

func (ErrorReasonArticle) Type() protoreflect.EnumType {
	return &file_blog_v1_error_proto_enumTypes[0]
}

func (x ErrorReasonArticle) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorReasonArticle.Descriptor instead.
func (ErrorReasonArticle) EnumDescriptor() ([]byte, []int) {
	return file_blog_v1_error_proto_rawDescGZIP(), []int{0}
}

// 标签模块错误 2021-2039
type ErrorReasonTag int32

const (
	ErrorReasonTag_TAG_NOT_FOUND ErrorReasonTag = 0 //标签不存在
)

// Enum value maps for ErrorReasonTag.
var (
	ErrorReasonTag_name = map[int32]string{
		0: "TAG_NOT_FOUND",
	}
	ErrorReasonTag_value = map[string]int32{
		"TAG_NOT_FOUND": 0,
	}
)

func (x ErrorReasonTag) Enum() *ErrorReasonTag {
	p := new(ErrorReasonTag)
	*p = x
	return p
}

func (x ErrorReasonTag) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorReasonTag) Descriptor() protoreflect.EnumDescriptor {
	return file_blog_v1_error_proto_enumTypes[1].Descriptor()
}

func (ErrorReasonTag) Type() protoreflect.EnumType {
	return &file_blog_v1_error_proto_enumTypes[1]
}

func (x ErrorReasonTag) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorReasonTag.Descriptor instead.
func (ErrorReasonTag) EnumDescriptor() ([]byte, []int) {
	return file_blog_v1_error_proto_rawDescGZIP(), []int{1}
}

var File_blog_v1_error_proto protoreflect.FileDescriptor

const file_blog_v1_error_proto_rawDesc = "" +
	"\n" +
	"\x13blog/v1/error.proto\x12\ablog.v1\x1a\x13errors/errors.proto*X\n" +
	"\x12ErrorReasonArticle\x12\x1f\n" +
	"\x15ARTICLE_ACCESS_DENIED\x10\x00\x1a\x04\xa8E\x93\x03\x12\x1b\n" +
	"\x11ARTICLE_NOT_FOUND\x10\x01\x1a\x04\xa8E\x94\x03\x1a\x04\xa0E\x90\x03*/\n" +
	"\x0eErrorReasonTag\x12\x17\n" +
	"\rTAG_NOT_FOUND\x10\x00\x1a\x04\xa8E\x94\x03\x1a\x04\xa0E\x90\x03B1Z/github.com/SoLikeWind/XuanXiang/api/blog/v1/;v1b\x06proto3"

var (
	file_blog_v1_error_proto_rawDescOnce sync.Once
	file_blog_v1_error_proto_rawDescData []byte
)

func file_blog_v1_error_proto_rawDescGZIP() []byte {
	file_blog_v1_error_proto_rawDescOnce.Do(func() {
		file_blog_v1_error_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_blog_v1_error_proto_rawDesc), len(file_blog_v1_error_proto_rawDesc)))
	})
	return file_blog_v1_error_proto_rawDescData
}

var file_blog_v1_error_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_blog_v1_error_proto_goTypes = []any{
	(ErrorReasonArticle)(0), // 0: blog.v1.ErrorReasonArticle
	(ErrorReasonTag)(0),     // 1: blog.v1.ErrorReasonTag
}
var file_blog_v1_error_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_blog_v1_error_proto_init() }
func file_blog_v1_error_proto_init() {
	if File_blog_v1_error_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_blog_v1_error_proto_rawDesc), len(file_blog_v1_error_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_blog_v1_error_proto_goTypes,
		DependencyIndexes: file_blog_v1_error_proto_depIdxs,
		EnumInfos:         file_blog_v1_error_proto_enumTypes,
	}.Build()
	File_blog_v1_error_proto = out.File
	file_blog_v1_error_proto_goTypes = nil
	file_blog_v1_error_proto_depIdxs = nil
}
