// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/SoLikeWind/XuanXiang/model/ent/article"
	"github.com/SoLikeWind/XuanXiang/model/ent/predicate"
	"github.com/SoLikeWind/XuanXiang/model/ent/tag"
)

// ArticleUpdate is the builder for updating Article entities.
type ArticleUpdate struct {
	config
	hooks    []Hook
	mutation *ArticleMutation
}

// Where appends a list predicates to the ArticleUpdate builder.
func (au *ArticleUpdate) Where(ps ...predicate.Article) *ArticleUpdate {
	au.mutation.Where(ps...)
	return au
}

// SetUpdatedAt sets the "updated_at" field.
func (au *ArticleUpdate) SetUpdatedAt(t time.Time) *ArticleUpdate {
	au.mutation.SetUpdatedAt(t)
	return au
}

// SetTitle sets the "title" field.
func (au *ArticleUpdate) SetTitle(s string) *ArticleUpdate {
	au.mutation.SetTitle(s)
	return au
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (au *ArticleUpdate) SetNillableTitle(s *string) *ArticleUpdate {
	if s != nil {
		au.SetTitle(*s)
	}
	return au
}

// SetSummary sets the "summary" field.
func (au *ArticleUpdate) SetSummary(s string) *ArticleUpdate {
	au.mutation.SetSummary(s)
	return au
}

// SetNillableSummary sets the "summary" field if the given value is not nil.
func (au *ArticleUpdate) SetNillableSummary(s *string) *ArticleUpdate {
	if s != nil {
		au.SetSummary(*s)
	}
	return au
}

// SetImage sets the "image" field.
func (au *ArticleUpdate) SetImage(s string) *ArticleUpdate {
	au.mutation.SetImage(s)
	return au
}

// SetNillableImage sets the "image" field if the given value is not nil.
func (au *ArticleUpdate) SetNillableImage(s *string) *ArticleUpdate {
	if s != nil {
		au.SetImage(*s)
	}
	return au
}

// ClearImage clears the value of the "image" field.
func (au *ArticleUpdate) ClearImage() *ArticleUpdate {
	au.mutation.ClearImage()
	return au
}

// SetContentMd sets the "content_md" field.
func (au *ArticleUpdate) SetContentMd(s string) *ArticleUpdate {
	au.mutation.SetContentMd(s)
	return au
}

// SetNillableContentMd sets the "content_md" field if the given value is not nil.
func (au *ArticleUpdate) SetNillableContentMd(s *string) *ArticleUpdate {
	if s != nil {
		au.SetContentMd(*s)
	}
	return au
}

// SetContentHTML sets the "content_html" field.
func (au *ArticleUpdate) SetContentHTML(s string) *ArticleUpdate {
	au.mutation.SetContentHTML(s)
	return au
}

// SetNillableContentHTML sets the "content_html" field if the given value is not nil.
func (au *ArticleUpdate) SetNillableContentHTML(s *string) *ArticleUpdate {
	if s != nil {
		au.SetContentHTML(*s)
	}
	return au
}

// SetViews sets the "views" field.
func (au *ArticleUpdate) SetViews(i int64) *ArticleUpdate {
	au.mutation.ResetViews()
	au.mutation.SetViews(i)
	return au
}

// SetNillableViews sets the "views" field if the given value is not nil.
func (au *ArticleUpdate) SetNillableViews(i *int64) *ArticleUpdate {
	if i != nil {
		au.SetViews(*i)
	}
	return au
}

// AddViews adds i to the "views" field.
func (au *ArticleUpdate) AddViews(i int64) *ArticleUpdate {
	au.mutation.AddViews(i)
	return au
}

// AddTagIDs adds the "tags" edge to the Tag entity by IDs.
func (au *ArticleUpdate) AddTagIDs(ids ...int) *ArticleUpdate {
	au.mutation.AddTagIDs(ids...)
	return au
}

// AddTags adds the "tags" edges to the Tag entity.
func (au *ArticleUpdate) AddTags(t ...*Tag) *ArticleUpdate {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return au.AddTagIDs(ids...)
}

// Mutation returns the ArticleMutation object of the builder.
func (au *ArticleUpdate) Mutation() *ArticleMutation {
	return au.mutation
}

// ClearTags clears all "tags" edges to the Tag entity.
func (au *ArticleUpdate) ClearTags() *ArticleUpdate {
	au.mutation.ClearTags()
	return au
}

// RemoveTagIDs removes the "tags" edge to Tag entities by IDs.
func (au *ArticleUpdate) RemoveTagIDs(ids ...int) *ArticleUpdate {
	au.mutation.RemoveTagIDs(ids...)
	return au
}

// RemoveTags removes "tags" edges to Tag entities.
func (au *ArticleUpdate) RemoveTags(t ...*Tag) *ArticleUpdate {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return au.RemoveTagIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (au *ArticleUpdate) Save(ctx context.Context) (int, error) {
	au.defaults()
	return withHooks(ctx, au.sqlSave, au.mutation, au.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (au *ArticleUpdate) SaveX(ctx context.Context) int {
	affected, err := au.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (au *ArticleUpdate) Exec(ctx context.Context) error {
	_, err := au.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (au *ArticleUpdate) ExecX(ctx context.Context) {
	if err := au.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (au *ArticleUpdate) defaults() {
	if _, ok := au.mutation.UpdatedAt(); !ok {
		v := article.UpdateDefaultUpdatedAt()
		au.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (au *ArticleUpdate) check() error {
	if v, ok := au.mutation.Title(); ok {
		if err := article.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Article.title": %w`, err)}
		}
	}
	if v, ok := au.mutation.Summary(); ok {
		if err := article.SummaryValidator(v); err != nil {
			return &ValidationError{Name: "summary", err: fmt.Errorf(`ent: validator failed for field "Article.summary": %w`, err)}
		}
	}
	if v, ok := au.mutation.Image(); ok {
		if err := article.ImageValidator(v); err != nil {
			return &ValidationError{Name: "image", err: fmt.Errorf(`ent: validator failed for field "Article.image": %w`, err)}
		}
	}
	if v, ok := au.mutation.ContentMd(); ok {
		if err := article.ContentMdValidator(v); err != nil {
			return &ValidationError{Name: "content_md", err: fmt.Errorf(`ent: validator failed for field "Article.content_md": %w`, err)}
		}
	}
	if v, ok := au.mutation.ContentHTML(); ok {
		if err := article.ContentHTMLValidator(v); err != nil {
			return &ValidationError{Name: "content_html", err: fmt.Errorf(`ent: validator failed for field "Article.content_html": %w`, err)}
		}
	}
	if v, ok := au.mutation.Views(); ok {
		if err := article.ViewsValidator(v); err != nil {
			return &ValidationError{Name: "views", err: fmt.Errorf(`ent: validator failed for field "Article.views": %w`, err)}
		}
	}
	return nil
}

func (au *ArticleUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := au.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(article.Table, article.Columns, sqlgraph.NewFieldSpec(article.FieldID, field.TypeInt64))
	if ps := au.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := au.mutation.UpdatedAt(); ok {
		_spec.SetField(article.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := au.mutation.Title(); ok {
		_spec.SetField(article.FieldTitle, field.TypeString, value)
	}
	if value, ok := au.mutation.Summary(); ok {
		_spec.SetField(article.FieldSummary, field.TypeString, value)
	}
	if value, ok := au.mutation.Image(); ok {
		_spec.SetField(article.FieldImage, field.TypeString, value)
	}
	if au.mutation.ImageCleared() {
		_spec.ClearField(article.FieldImage, field.TypeString)
	}
	if value, ok := au.mutation.ContentMd(); ok {
		_spec.SetField(article.FieldContentMd, field.TypeString, value)
	}
	if value, ok := au.mutation.ContentHTML(); ok {
		_spec.SetField(article.FieldContentHTML, field.TypeString, value)
	}
	if value, ok := au.mutation.Views(); ok {
		_spec.SetField(article.FieldViews, field.TypeInt64, value)
	}
	if value, ok := au.mutation.AddedViews(); ok {
		_spec.AddField(article.FieldViews, field.TypeInt64, value)
	}
	if au.mutation.TagsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   article.TagsTable,
			Columns: article.TagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.RemovedTagsIDs(); len(nodes) > 0 && !au.mutation.TagsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   article.TagsTable,
			Columns: article.TagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.TagsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   article.TagsTable,
			Columns: article.TagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, au.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{article.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	au.mutation.done = true
	return n, nil
}

// ArticleUpdateOne is the builder for updating a single Article entity.
type ArticleUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ArticleMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (auo *ArticleUpdateOne) SetUpdatedAt(t time.Time) *ArticleUpdateOne {
	auo.mutation.SetUpdatedAt(t)
	return auo
}

// SetTitle sets the "title" field.
func (auo *ArticleUpdateOne) SetTitle(s string) *ArticleUpdateOne {
	auo.mutation.SetTitle(s)
	return auo
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (auo *ArticleUpdateOne) SetNillableTitle(s *string) *ArticleUpdateOne {
	if s != nil {
		auo.SetTitle(*s)
	}
	return auo
}

// SetSummary sets the "summary" field.
func (auo *ArticleUpdateOne) SetSummary(s string) *ArticleUpdateOne {
	auo.mutation.SetSummary(s)
	return auo
}

// SetNillableSummary sets the "summary" field if the given value is not nil.
func (auo *ArticleUpdateOne) SetNillableSummary(s *string) *ArticleUpdateOne {
	if s != nil {
		auo.SetSummary(*s)
	}
	return auo
}

// SetImage sets the "image" field.
func (auo *ArticleUpdateOne) SetImage(s string) *ArticleUpdateOne {
	auo.mutation.SetImage(s)
	return auo
}

// SetNillableImage sets the "image" field if the given value is not nil.
func (auo *ArticleUpdateOne) SetNillableImage(s *string) *ArticleUpdateOne {
	if s != nil {
		auo.SetImage(*s)
	}
	return auo
}

// ClearImage clears the value of the "image" field.
func (auo *ArticleUpdateOne) ClearImage() *ArticleUpdateOne {
	auo.mutation.ClearImage()
	return auo
}

// SetContentMd sets the "content_md" field.
func (auo *ArticleUpdateOne) SetContentMd(s string) *ArticleUpdateOne {
	auo.mutation.SetContentMd(s)
	return auo
}

// SetNillableContentMd sets the "content_md" field if the given value is not nil.
func (auo *ArticleUpdateOne) SetNillableContentMd(s *string) *ArticleUpdateOne {
	if s != nil {
		auo.SetContentMd(*s)
	}
	return auo
}

// SetContentHTML sets the "content_html" field.
func (auo *ArticleUpdateOne) SetContentHTML(s string) *ArticleUpdateOne {
	auo.mutation.SetContentHTML(s)
	return auo
}

// SetNillableContentHTML sets the "content_html" field if the given value is not nil.
func (auo *ArticleUpdateOne) SetNillableContentHTML(s *string) *ArticleUpdateOne {
	if s != nil {
		auo.SetContentHTML(*s)
	}
	return auo
}

// SetViews sets the "views" field.
func (auo *ArticleUpdateOne) SetViews(i int64) *ArticleUpdateOne {
	auo.mutation.ResetViews()
	auo.mutation.SetViews(i)
	return auo
}

// SetNillableViews sets the "views" field if the given value is not nil.
func (auo *ArticleUpdateOne) SetNillableViews(i *int64) *ArticleUpdateOne {
	if i != nil {
		auo.SetViews(*i)
	}
	return auo
}

// AddViews adds i to the "views" field.
func (auo *ArticleUpdateOne) AddViews(i int64) *ArticleUpdateOne {
	auo.mutation.AddViews(i)
	return auo
}

// AddTagIDs adds the "tags" edge to the Tag entity by IDs.
func (auo *ArticleUpdateOne) AddTagIDs(ids ...int) *ArticleUpdateOne {
	auo.mutation.AddTagIDs(ids...)
	return auo
}

// AddTags adds the "tags" edges to the Tag entity.
func (auo *ArticleUpdateOne) AddTags(t ...*Tag) *ArticleUpdateOne {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return auo.AddTagIDs(ids...)
}

// Mutation returns the ArticleMutation object of the builder.
func (auo *ArticleUpdateOne) Mutation() *ArticleMutation {
	return auo.mutation
}

// ClearTags clears all "tags" edges to the Tag entity.
func (auo *ArticleUpdateOne) ClearTags() *ArticleUpdateOne {
	auo.mutation.ClearTags()
	return auo
}

// RemoveTagIDs removes the "tags" edge to Tag entities by IDs.
func (auo *ArticleUpdateOne) RemoveTagIDs(ids ...int) *ArticleUpdateOne {
	auo.mutation.RemoveTagIDs(ids...)
	return auo
}

// RemoveTags removes "tags" edges to Tag entities.
func (auo *ArticleUpdateOne) RemoveTags(t ...*Tag) *ArticleUpdateOne {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return auo.RemoveTagIDs(ids...)
}

// Where appends a list predicates to the ArticleUpdate builder.
func (auo *ArticleUpdateOne) Where(ps ...predicate.Article) *ArticleUpdateOne {
	auo.mutation.Where(ps...)
	return auo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (auo *ArticleUpdateOne) Select(field string, fields ...string) *ArticleUpdateOne {
	auo.fields = append([]string{field}, fields...)
	return auo
}

// Save executes the query and returns the updated Article entity.
func (auo *ArticleUpdateOne) Save(ctx context.Context) (*Article, error) {
	auo.defaults()
	return withHooks(ctx, auo.sqlSave, auo.mutation, auo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (auo *ArticleUpdateOne) SaveX(ctx context.Context) *Article {
	node, err := auo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (auo *ArticleUpdateOne) Exec(ctx context.Context) error {
	_, err := auo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (auo *ArticleUpdateOne) ExecX(ctx context.Context) {
	if err := auo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (auo *ArticleUpdateOne) defaults() {
	if _, ok := auo.mutation.UpdatedAt(); !ok {
		v := article.UpdateDefaultUpdatedAt()
		auo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (auo *ArticleUpdateOne) check() error {
	if v, ok := auo.mutation.Title(); ok {
		if err := article.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Article.title": %w`, err)}
		}
	}
	if v, ok := auo.mutation.Summary(); ok {
		if err := article.SummaryValidator(v); err != nil {
			return &ValidationError{Name: "summary", err: fmt.Errorf(`ent: validator failed for field "Article.summary": %w`, err)}
		}
	}
	if v, ok := auo.mutation.Image(); ok {
		if err := article.ImageValidator(v); err != nil {
			return &ValidationError{Name: "image", err: fmt.Errorf(`ent: validator failed for field "Article.image": %w`, err)}
		}
	}
	if v, ok := auo.mutation.ContentMd(); ok {
		if err := article.ContentMdValidator(v); err != nil {
			return &ValidationError{Name: "content_md", err: fmt.Errorf(`ent: validator failed for field "Article.content_md": %w`, err)}
		}
	}
	if v, ok := auo.mutation.ContentHTML(); ok {
		if err := article.ContentHTMLValidator(v); err != nil {
			return &ValidationError{Name: "content_html", err: fmt.Errorf(`ent: validator failed for field "Article.content_html": %w`, err)}
		}
	}
	if v, ok := auo.mutation.Views(); ok {
		if err := article.ViewsValidator(v); err != nil {
			return &ValidationError{Name: "views", err: fmt.Errorf(`ent: validator failed for field "Article.views": %w`, err)}
		}
	}
	return nil
}

func (auo *ArticleUpdateOne) sqlSave(ctx context.Context) (_node *Article, err error) {
	if err := auo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(article.Table, article.Columns, sqlgraph.NewFieldSpec(article.FieldID, field.TypeInt64))
	id, ok := auo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Article.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := auo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, article.FieldID)
		for _, f := range fields {
			if !article.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != article.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := auo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := auo.mutation.UpdatedAt(); ok {
		_spec.SetField(article.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := auo.mutation.Title(); ok {
		_spec.SetField(article.FieldTitle, field.TypeString, value)
	}
	if value, ok := auo.mutation.Summary(); ok {
		_spec.SetField(article.FieldSummary, field.TypeString, value)
	}
	if value, ok := auo.mutation.Image(); ok {
		_spec.SetField(article.FieldImage, field.TypeString, value)
	}
	if auo.mutation.ImageCleared() {
		_spec.ClearField(article.FieldImage, field.TypeString)
	}
	if value, ok := auo.mutation.ContentMd(); ok {
		_spec.SetField(article.FieldContentMd, field.TypeString, value)
	}
	if value, ok := auo.mutation.ContentHTML(); ok {
		_spec.SetField(article.FieldContentHTML, field.TypeString, value)
	}
	if value, ok := auo.mutation.Views(); ok {
		_spec.SetField(article.FieldViews, field.TypeInt64, value)
	}
	if value, ok := auo.mutation.AddedViews(); ok {
		_spec.AddField(article.FieldViews, field.TypeInt64, value)
	}
	if auo.mutation.TagsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   article.TagsTable,
			Columns: article.TagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.RemovedTagsIDs(); len(nodes) > 0 && !auo.mutation.TagsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   article.TagsTable,
			Columns: article.TagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.TagsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   article.TagsTable,
			Columns: article.TagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Article{config: auo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, auo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{article.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	auo.mutation.done = true
	return _node, nil
}
