syntax = "proto3";

package common.model;

import "google/protobuf/timestamp.proto";

option go_package = "github.com/SoLikeWind/XuanXiang/api/common/model;model";

// 文章
message Article {
    // 文章ID
    int64 id = 1;
    // 文章标题
    string title = 2;
    // 文章摘要
    string summary = 3;
    // 文章封面
    string image = 4;
    // 文章Markdown内容
    string content_md = 5;
    // 文章HTML内容
    string content_html = 6;
    // 文章浏览量
    int64 views = 7;
    // 文章标签
    repeated ArticleTag tags = 8;
    // 文章创建时间
    google.protobuf.Timestamp created_at = 9;
    // 文章更新时间
    google.protobuf.Timestamp updated_at = 10;
}

// 文章标签
message ArticleTag {
    // 标签ID
    int64 id = 1;
    // 文章ID
    int64 article_id = 2;
    // 标签名称
    string name = 3;

}

message User {
    int64 id = 1;
    string account = 2;
    string password = 3;
    string name = 4;
    string icon = 5;
    string email = 6; // 可选
    string sign = 7;  // 可选
    repeated Article articles = 8; // 关联的文章
    // repeated Tag tags = 9;
}