// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.0
// source: common/model/blog_model.proto

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 文章
type Article struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 文章ID
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 文章标题
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// 文章摘要
	Summary string `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"`
	// 文章封面
	Image string `protobuf:"bytes,4,opt,name=image,proto3" json:"image,omitempty"`
	// 文章Markdown内容
	ContentMd string `protobuf:"bytes,5,opt,name=content_md,json=contentMd,proto3" json:"content_md,omitempty"`
	// 文章HTML内容
	ContentHtml string `protobuf:"bytes,6,opt,name=content_html,json=contentHtml,proto3" json:"content_html,omitempty"`
	// 文章浏览量
	Views int64 `protobuf:"varint,7,opt,name=views,proto3" json:"views,omitempty"`
	// 文章标签
	Tags []*ArticleTag `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty"`
	// 文章创建时间
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// 文章更新时间
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Article) Reset() {
	*x = Article{}
	mi := &file_common_model_blog_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Article) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Article) ProtoMessage() {}

func (x *Article) ProtoReflect() protoreflect.Message {
	mi := &file_common_model_blog_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Article.ProtoReflect.Descriptor instead.
func (*Article) Descriptor() ([]byte, []int) {
	return file_common_model_blog_model_proto_rawDescGZIP(), []int{0}
}

func (x *Article) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Article) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Article) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *Article) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *Article) GetContentMd() string {
	if x != nil {
		return x.ContentMd
	}
	return ""
}

func (x *Article) GetContentHtml() string {
	if x != nil {
		return x.ContentHtml
	}
	return ""
}

func (x *Article) GetViews() int64 {
	if x != nil {
		return x.Views
	}
	return 0
}

func (x *Article) GetTags() []*ArticleTag {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Article) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Article) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// 文章标签
type ArticleTag struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 标签ID
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 文章ID
	ArticleId int64 `protobuf:"varint,2,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	// 标签名称
	Name          string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArticleTag) Reset() {
	*x = ArticleTag{}
	mi := &file_common_model_blog_model_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArticleTag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArticleTag) ProtoMessage() {}

func (x *ArticleTag) ProtoReflect() protoreflect.Message {
	mi := &file_common_model_blog_model_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArticleTag.ProtoReflect.Descriptor instead.
func (*ArticleTag) Descriptor() ([]byte, []int) {
	return file_common_model_blog_model_proto_rawDescGZIP(), []int{1}
}

func (x *ArticleTag) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ArticleTag) GetArticleId() int64 {
	if x != nil {
		return x.ArticleId
	}
	return 0
}

func (x *ArticleTag) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Account       string                 `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Icon          string                 `protobuf:"bytes,5,opt,name=icon,proto3" json:"icon,omitempty"`
	Email         string                 `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`       // 可选
	Sign          string                 `protobuf:"bytes,7,opt,name=sign,proto3" json:"sign,omitempty"`         // 可选
	Articles      []*Article             `protobuf:"bytes,8,rep,name=articles,proto3" json:"articles,omitempty"` // 关联的文章
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_common_model_blog_model_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_common_model_blog_model_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_common_model_blog_model_proto_rawDescGZIP(), []int{2}
}

func (x *User) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *User) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetSign() string {
	if x != nil {
		return x.Sign
	}
	return ""
}

func (x *User) GetArticles() []*Article {
	if x != nil {
		return x.Articles
	}
	return nil
}

var File_common_model_blog_model_proto protoreflect.FileDescriptor

const file_common_model_blog_model_proto_rawDesc = "" +
	"\n" +
	"\x1dcommon/model/blog_model.proto\x12\fcommon.model\x1a\x1fgoogle/protobuf/timestamp.proto\"\xdb\x02\n" +
	"\aArticle\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\asummary\x18\x03 \x01(\tR\asummary\x12\x14\n" +
	"\x05image\x18\x04 \x01(\tR\x05image\x12\x1d\n" +
	"\n" +
	"content_md\x18\x05 \x01(\tR\tcontentMd\x12!\n" +
	"\fcontent_html\x18\x06 \x01(\tR\vcontentHtml\x12\x14\n" +
	"\x05views\x18\a \x01(\x03R\x05views\x12,\n" +
	"\x04tags\x18\b \x03(\v2\x18.common.model.ArticleTagR\x04tags\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"O\n" +
	"\n" +
	"ArticleTag\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"article_id\x18\x02 \x01(\x03R\tarticleId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"\xd1\x01\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x18\n" +
	"\aaccount\x18\x02 \x01(\tR\aaccount\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x12\n" +
	"\x04icon\x18\x05 \x01(\tR\x04icon\x12\x14\n" +
	"\x05email\x18\x06 \x01(\tR\x05email\x12\x12\n" +
	"\x04sign\x18\a \x01(\tR\x04sign\x121\n" +
	"\barticles\x18\b \x03(\v2\x15.common.model.ArticleR\barticlesB8Z6github.com/SoLikeWind/XuanXiang/api/common/model;modelb\x06proto3"

var (
	file_common_model_blog_model_proto_rawDescOnce sync.Once
	file_common_model_blog_model_proto_rawDescData []byte
)

func file_common_model_blog_model_proto_rawDescGZIP() []byte {
	file_common_model_blog_model_proto_rawDescOnce.Do(func() {
		file_common_model_blog_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_model_blog_model_proto_rawDesc), len(file_common_model_blog_model_proto_rawDesc)))
	})
	return file_common_model_blog_model_proto_rawDescData
}

var file_common_model_blog_model_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_common_model_blog_model_proto_goTypes = []any{
	(*Article)(nil),               // 0: common.model.Article
	(*ArticleTag)(nil),            // 1: common.model.ArticleTag
	(*User)(nil),                  // 2: common.model.User
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_common_model_blog_model_proto_depIdxs = []int32{
	1, // 0: common.model.Article.tags:type_name -> common.model.ArticleTag
	3, // 1: common.model.Article.created_at:type_name -> google.protobuf.Timestamp
	3, // 2: common.model.Article.updated_at:type_name -> google.protobuf.Timestamp
	0, // 3: common.model.User.articles:type_name -> common.model.Article
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_common_model_blog_model_proto_init() }
func file_common_model_blog_model_proto_init() {
	if File_common_model_blog_model_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_model_blog_model_proto_rawDesc), len(file_common_model_blog_model_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_model_blog_model_proto_goTypes,
		DependencyIndexes: file_common_model_blog_model_proto_depIdxs,
		MessageInfos:      file_common_model_blog_model_proto_msgTypes,
	}.Build()
	File_common_model_blog_model_proto = out.File
	file_common_model_blog_model_proto_goTypes = nil
	file_common_model_blog_model_proto_depIdxs = nil
}
